# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(909, 687)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.cameraView = QtWidgets.QLabel(Form)
        self.cameraView.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraView.setLineWidth(1)
        self.cameraView.setObjectName("cameraView")
        self.verticalLayout_2.addWidget(self.cameraView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exLevel = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.exLevel.setFont(font)
        self.exLevel.setObjectName("exLevel")
        self.exLevel.addItem("")
        self.exLevel.addItem("")
        self.exLevel.addItem("")
        self.horizontalLayout.addWidget(self.exLevel)
        self.faceReco = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.faceReco.setFont(font)
        self.faceReco.setObjectName("faceReco")
        self.horizontalLayout.addWidget(self.faceReco)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PM_True = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(14)
        self.PM_True.setFont(font)
        self.PM_True.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.PM_True.setObjectName("PM_True")
        self.horizontalLayout_2.addWidget(self.PM_True)
        self.PM_Fault = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(14)
        self.PM_Fault.setFont(font)
        self.PM_Fault.setStyleSheet("background-color: rgb(255, 88, 66);")
        self.PM_Fault.setObjectName("PM_Fault")
        self.horizontalLayout_2.addWidget(self.PM_Fault)
        self.assignment = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.assignment.setFont(font)
        self.assignment.setObjectName("assignment")
        self.horizontalLayout_2.addWidget(self.assignment)
        self.print = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(14)
        self.print.setFont(font)
        self.print.setObjectName("print")
        self.horizontalLayout_2.addWidget(self.print)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeShower = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeShower.sizePolicy().hasHeightForWidth())
        self.timeShower.setSizePolicy(sizePolicy)
        self.timeShower.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.timeShower.setFont(font)
        self.timeShower.setObjectName("timeShower")
        self.verticalLayout.addWidget(self.timeShower)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.identityView = QtWidgets.QLabel(self.groupBox)
        self.identityView.setFrameShape(QtWidgets.QFrame.Box)
        self.identityView.setAlignment(QtCore.Qt.AlignCenter)
        self.identityView.setObjectName("identityView")
        self.gridLayout_4.addWidget(self.identityView, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.nameText = QtWidgets.QLabel(self.groupBox)
        self.nameText.setText("")
        self.nameText.setObjectName("nameText")
        self.gridLayout_2.addWidget(self.nameText, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.IDText = QtWidgets.QLabel(self.groupBox)
        self.IDText.setText("")
        self.IDText.setObjectName("IDText")
        self.gridLayout_2.addWidget(self.IDText, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.exLocation = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(18)
        self.exLocation.setFont(font)
        self.exLocation.setObjectName("exLocation")
        self.gridLayout.addWidget(self.exLocation, 1, 1, 1, 1)
        self.exNumber = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.exNumber.setFont(font)
        self.exNumber.setObjectName("exNumber")
        self.gridLayout.addWidget(self.exNumber, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.exPosition = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Adobe 楷体 Std R")
        font.setPointSize(18)
        self.exPosition.setFont(font)
        self.exPosition.setObjectName("exPosition")
        self.gridLayout.addWidget(self.exPosition, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "人脸识别考场分配系统"))
        self.label.setText(_translate("Form", "欢迎使用人脸识别考场分配系统"))
        self.cameraView.setText(_translate("Form", "TextLabel"))
        self.exLevel.setItemText(0, _translate("Form", "请选择等级"))
        self.exLevel.setItemText(1, _translate("Form", "大学英语四级考试"))
        self.exLevel.setItemText(2, _translate("Form", "大学英语六级考试"))
        self.faceReco.setText(_translate("Form", "人脸识别"))
        self.PM_True.setText(_translate("Form", "身份信息正确并分配考场"))
        self.PM_Fault.setText(_translate("Form", "身份信息错误"))
        self.assignment.setText(_translate("Form", "分配考场"))
        self.print.setText(_translate("Form", "打印"))
        self.timeShower.setText(_translate("Form", "TextLabel"))
        self.groupBox.setTitle(_translate("Form", "身份信息"))
        self.identityView.setText(_translate("Form", "登记照片"))
        self.label_2.setText(_translate("Form", "姓名："))
        self.label_3.setText(_translate("Form", "工号："))
        self.groupBox_2.setTitle(_translate("Form", "您分配到的考场信息"))
        self.label_4.setText(_translate("Form", "考场号："))
        self.exLocation.setText(_translate("Form", "待分配"))
        self.exNumber.setText(_translate("Form", "XXX"))
        self.label_6.setText(_translate("Form", "考场位置："))
        self.label_5.setText(_translate("Form", "监考身份："))
        self.exPosition.setText(_translate("Form", "待分配"))
